# Generated by Django 4.1.7 on 2023-03-29 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_dish'),
    ]

    operations = [
        migrations.AddField(
            model_name='submenu',
            name='dish_count',
            field=models.IntegerField(default=0),
        ),
    ]
