# Generated by Django 4.1.7 on 2023-03-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_dish_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='dish_count',
            field=models.IntegerField(default=0),
        ),
    ]
